services:
  fast-test-cvs:
    container_name: fast-test-cvs
    image: fast-test-cvs:dev
    restart: unless-stopped
    ports:
      - "85:80"
    env_file:
      - src/.env
    depends_on:
      - postgres
      # - mssqlserver

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=quiz_app
      - POSTGRES_USER=brent
      - POSTGRES_PASSWORD=Password123
    # volumes:
    #   - postgres-data:/var/lib/postgresql/db


  mssqlserver:
    # platform: linux
    container_name: mssqlserver
    image: mcr.microsoft.com/azure-sql-edge:latest
    # image: mcr.microsoft.com/mssql/server:latest
    environment:
        - ACCEPT_EULA=1
        - MSSQL_PID=Developer
        - MSSQL_USER=sa
        - MSSQL_SA_PASSWORD=Password123
    ports:
        - 1433:1433
    hostname: mssqlserver22
    # volumes:
    #     - ./data:/var/opt/mssql/data
    #     - ./log:/var/opt/mssql/log
    #     - ./secrets:/var/opt/mssql/secrets