services:
  fast-test-cvs:
    container_name: fast-test-cvs
    image: fast-test-cvs:dev
    restart: unless-stopped
    ports:
      - "85:80"
    # env_file:

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=quiz-app
      - POSTGRES_USER=brent
      - POSTGRES_PASSWORD=admin
    # volumes:
    #   - postgres-data:/var/lib/postgresql/db