name: Dev Build and Deploy

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on:
      group: cvs-linux-self-hosted
    environment:
      name: 'dev'
    steps:
    - name: Checkout Github Action
      uses: actions/checkout@v2

    - name: Copy .env file
      run: |
        echo "${{ secrets.ENV }}" > src/.env

    - name: Login to Quay
      run: echo "${{ secrets.DOCKER_REGISTRY_PASSWORD }}" | docker login harbor.domain.com -u ${{ secrets.DOCKER_REGISTRY_USER }} --password-stdin

    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Build and push Docker image
      run: |
        az acr login --name ${{ vars.AZURE_REGISTRY_NAME }}
        docker build . -t ${{ vars.AZURE_REGISTRY_URL }}/${{ vars.DOCKER_IMAGE }}:${{ github.sha }}
        docker push ${{ vars.AZURE_REGISTRY_URL }}/${{ vars.DOCKER_IMAGE }}:${{ github.sha }} 

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ vars.AZURE_APP_NAME }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        images: '${{ vars.AZURE_REGISTRY_URL }}/${{ vars.DOCKER_IMAGE }}:${{ github.sha }}'