on:
  push:
    # branches:
    #   - main


jobs:
  env:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Checkout code2
      run: |
        echo "Hello ${{ env.QUAY_PASSWORD }} ${{ env.QUAY_USERNAME }}"

    # - name: Build Docker image
    #   run: |
    #     ls -la

    - name: Build Docker image
      run: |
        docker build -t fast-test-cvs:latest .

    # - name: Login to Quay.io
    #   run: |
    #     echo ${{ env.QUAY_PASSWORD }} | docker login quay-registry.aetna.com -u ${{ env.QUAY_USERNAME }} --password-stdin

    # - name: Push to Quay.io
    #   run: |
    #     docker tag fast-test-cvs:latest quay-registry.aetna.com/${{ env.QUAY_USERNAME }}/fast-test-cvs:latest
    #     docker push quay-registry.aetna.com/${{ env.QUAY_USERNAME }}/fast-test-cvs:latest


# name: Deploy FastAPI to Quay.io and Azure App Service

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Set up Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: '3.9'

#     - name: Install Poetry
#       run: |
#         curl -sSL https://install.python-poetry.org | python3 -

#     - name: Install dependencies
#       run: |
#         poetry install

#     - name: Build Docker image
#       run: |
#         docker build -t fast-test-cvs:latest .

#     - name: Login to Quay.io
#       run: |
#         echo ${{ env.QUAY_PASSWORD }} | docker login quay-registry.aetna.com -u ${{ env.QUAY_USERNAME }} --password-stdin

#     - name: Push to Quay.io
#       run: |
#         docker tag fast-test-cvs:latest quay-registry.aetna.com/${{ env.QUAY_USERNAME }}/fast-test-cvs:latest
#         docker push quay-registry.aetna.com/${{ env.QUAY_USERNAME }}/fast-test-cvs:latest

    # - name: Login to Azure
    #   uses: azure/login@v1
    #   with:
    #     creds: ${{ secrets.AZURE_CREDENTIALS }}

    # - name: Deploy to Azure App Service
    #   run: |
    #     az webapp config container set --name ${{ secrets.APP_SERVICE_NAME }} \
    #       --resource-group ${{ secrets.RESOURCE_GROUP }} \
    #       --docker-custom-image-name quay.io/${{ secrets.QUAY_USERNAME }}/fast-test-cvs:latest \
    #       --docker-registry-server-url https://quay.io \
    #       --docker-registry-server-user ${{ secrets.QUAY_USERNAME }} \
    #       --docker-registry-server-password ${{ secrets.QUAY_PASSWORD }}

    # - name: Restart Azure App Service
    #   run: |
    #     az webapp restart --name ${{ secrets.APP_SERVICE_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }}
